// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import model "auth-service/internal/model"

// App is an autogenerated mock type for the App type
type App struct {
	mock.Mock
}

// RefreshTokens provides a mock function with given fields: ctx, refreshToken
func (_m *App) RefreshTokens(ctx context.Context, refreshToken string) (model.Tokens, error) {
	ret := _m.Called(ctx, refreshToken)

	var r0 model.Tokens
	if rf, ok := ret.Get(0).(func(context.Context, string) model.Tokens); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(model.Tokens)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignIn provides a mock function with given fields: ctx, user
func (_m *App) SignIn(ctx context.Context, user model.User) (model.Tokens, error) {
	ret := _m.Called(ctx, user)

	var r0 model.Tokens
	if rf, ok := ret.Get(0).(func(context.Context, model.User) model.Tokens); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(model.Tokens)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
