// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "auth-service/internal/model"

// Tokenizer is an autogenerated mock type for the Tokenizer type
type Tokenizer struct {
	mock.Mock
}

// NewTokens provides a mock function with given fields: guid
func (_m *Tokenizer) NewTokens(guid string) (model.Tokens, error) {
	ret := _m.Called(guid)

	var r0 model.Tokens
	if rf, ok := ret.Get(0).(func(string) model.Tokens); ok {
		r0 = rf(guid)
	} else {
		r0 = ret.Get(0).(model.Tokens)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(guid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
